service: cliente-auth-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:AdminGetUser
      Resource: "arn:aws:cognito-idp:us-east-1:411879454356:userpool/us-east-1_hd78hK5KF"

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
